### ISSUE TITLE
RiskProfiler.ca does not show up in Google search results (SEO etc.)

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#126]
Our website https://www.riskprofiler.ca/ does not appear in Google, Bing or DuckDuckGo search results.
We really need to improve our SEO.

### Details

When searching for just "RiskProfiler", top results are on "riskprofiler.io" (understandable),
but even when explicitly searching for "RiskProfiler.ca", the top results are either:

- https://www.publicsafety.gc.ca/cnt/mrgnc-mngmnt/ntnl-rsk-prfl/index-en.aspx (Google)
- https://natural-resources.canada.ca/simply-science/new-tool-assess-earthquake-risks-canada/25202 (Bing, and therefore DuckDuckGo, Yahoo!)

Interestingly, our Pygeoapi pages https://geo-api.riskprofiler.ca/, and GitHub repos (e.g. OpenDRR/riskprofiler), https://geoscan.nrcan.gc.ca/starweb/geoscan/servlet.starweb?path=geoscan/fullf.web&search1=R=331875 show up in the search results, but https://www.riskprofiler.ca/ itself is nowhere to be seen.

### Suggested remedies

Suggestions from fellow EMS members

- Improve SEO (search engine optimization).

    For example, Open Graph meta tags could be added as a minimum?  E.g., from https://climatedata.ca/:

    ```html
	<!-- This site is optimized with the Yoast SEO plugin v21.2 - https://yoast.com/wordpress/plugins/seo/ -->
	<title>Home &#8212; ClimateData.ca</title>
	<meta name="description" content="ClimateData.ca provides high-resolution climate data to help decision makers build a more resilient Canada." />
	<link rel="canonical" href="https://climatedata.ca/" />
	<meta property="og:locale" content="en_US" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Home &#8212; ClimateData.ca" />
	<meta property="og:description" content="ClimateData.ca provides high-resolution climate data to help decision makers build a more resilient Canada." />
	<meta property="og:url" content="https://climatedata.ca/" />
	<meta property="og:site_name" content="ClimateData.ca" />
	<meta property="article:publisher" content="https://www.facebook.com/ClimateData.ca.Donneesclimatiques.ca" />
	<meta property="article:modified_time" content="2023-06-09T14:37:18+00:00" />
	<meta name="twitter:card" content="summary_large_image" />
	<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://climatedata.ca/","url":"https://climatedata.ca/","name":"Home &#8212; ClimateData.ca","isPartOf":{"@id":"https://donneesclimatiques.ca/#website"},"about":{"@id":"https://donneesclimatiques.ca/#organization"},"datePublished":"2019-01-15T20:11:28+00:00","dateModified":"2023-06-09T14:37:18+00:00","description":"ClimateData.ca provides high-resolution climate data to help decision makers build a more resilient Canada.","breadcrumb":{"@id":"https://climatedata.ca/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://climatedata.ca/"]}]},{"@type":"BreadcrumbList","@id":"https://climatedata.ca/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home"}]},{"@type":"WebSite","@id":"https://donneesclimatiques.ca/#website","url":"https://donneesclimatiques.ca/","name":"ClimateData.ca","description":"ClimateData.ca provides high-resolution climate data to help decision makers build a more resilient Canada.","publisher":{"@id":"https://donneesclimatiques.ca/#organization"},"alternateName":"ClimateData.ca","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://donneesclimatiques.ca/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://donneesclimatiques.ca/#organization","name":"ClimateData.ca","alternateName":"ClimateData.ca","url":"https://donneesclimatiques.ca/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://donneesclimatiques.ca/#/schema/logo/image/","url":"https://donneesclimatiques.ca/site/assets/uploads/2023/05/logo-climate-data-ca-1.png","contentUrl":"https://donneesclimatiques.ca/site/assets/uploads/2023/05/logo-climate-data-ca-1.png","width":600,"height":600,"caption":"ClimateData.ca"},"image":{"@id":"https://donneesclimatiques.ca/#/schema/logo/image/"},"sameAs":["https://www.facebook.com/ClimateData.ca.Donneesclimatiques.ca","https://www.linkedin.com/company/climate-data-canada/"]}]}</script>
	<!-- / Yoast SEO plugin. -->
    ```

- Continue the effort to get https://www.riskprofiler.ca/ listed in more NRCan and other Government of Canada web pages

### Special thanks

Many thanks to Meg (@MPConda) for bringing it up during our EMS meeting on 2024-04-09,
and to Joost (@jvanulde) and Jordan (@jordanharding) for providing expert advice!

### Tasks

- [ ] Correct the erroneous `<meta name="robots" content="noindex, nofollow">` on production site by changing WordPress setting; see also https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag
- [ ] Add `<meta name="robots" content="noindex, nofollow">` manually in our "Deploy to GitHub Pages" workflow so our preview site at <https://opendrr.github.io/riskprofiler/> does not get indexed by Google et al.
- [ ] Install Yoast SEO plugin
- [ ] Install a proper /robots.txt file
- [ ] [To be discussed] Change canonical domain name from https://www.riskprofiler.ca/ to https://riskprofiler.ca/ (i.e. use apex domain instead of www subdomain?), including doing proper (301?) redirection, updating our documentation where necessary, etc.
- [ ] Monitor our ranking in search engines, and see how it improves over time.

**Comment by anthonyfok** [comment]
Following up with my previous comment, WordPress plugins that help with SEO:

- [SEO for everyone • Yoast](https://yoast.com/)
- [The SEO Framework • Plugins that deliver results](https://theseoframework.com/)

Yoast is being used on https://climatedata.ca/ and on https://geo.ca/, for example (e.g. the `<script type="application/ld+json" class="yoast-schema-graph">` tags found there, so that's a good reference for us.

@jvanulde suggested "microdata markup" to me in a recent bilat.  He also wrote on 2024-05-27 in an email to the Open Science Data Platform team (attachment on Jira ticket OSDP-1718):

> Regarding the standard on web interoperability please see Appendix E in https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=25875
>
> Perhaps OSDP is compliant via shadow-DOM? I don’t see any microdata markup in the pages. No concept of a catalogue, a dataset, or spatial extent is evident. Again, perhaps it’s in the shadow-DOM… but I didn’t see it.
>
> You can use the structured data testing tool at Google to see how search engines see your resources: <https://validator.schema.org/>.
>
> I was one of the authors of that standard so I’m happy to support if needed.
>
> Joost

Comparing Schema validator results between geo.ca and riskprofiler.ca:

- https://validator.schema.org/#url=https%3A%2F%2Fgeo.ca%2Fhome%2F
- https://validator.schema.org/#url=https%3A%2F%2Fwww.riskprofiler.ca%2F (returns "No items detected")

**Comment by jordanharding** [comment]
Just adding my two cents here as an seo expert

Most importantly... This site is currently completely blocked from crawling, likely the wordpress setting that says "discourage search engines from indexing this site"

the tag generated by this setting is right in the page source: 

`<meta name="robots" content="noindex, nofollow">`

https://riskprofiler.ca/robots.txt - this **really** needs to be a valid file and accessible.

root canonical url should be https://riskprofiler.ca/ and not https://riskprofiler.ca/index.html

Hope this helps!

**Comment by anthonyfok** [comment]
@jordanharding, Thank you so much for sharing your great insight!  No wonder RiskProfiler.ca does not show up in Google at all, and OSDP (https://osdp-psdo.canada.ca/) does appear in the 3rd result despite not having Schema (Microdata and/or LD-JSON) (I'm a total SEO newbie.  😅)

@chloe2407 It would be great if you could work on this as time permits, and I'll be happy to help you get started.  Thanks!

**Comment by anthonyfok** [comment]
Location: Settings > Reading > Discourage search engines from indexing this site

![image](https://github.com/user-attachments/assets/509aaa38-4982-4e9f-8c6d-91e3603f23d8)

When “☑ Discourage search engines from indexing this site” is enabled:

```html
<meta name='robots' content='noindex, nofollow' />
```

When “☐ Discourage search engines from indexing this site” is disabled:

```html
<meta name='robots' content='max-image-preview:large' />
```

**Comment by jordanharding** [comment]
sign up on here if you haven't already

https://search.google.com/search-console

it will clearly tell you any issues that still persist.
